# Generated by Django 5.2.4 on 2025-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('download_link', models.URLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
