# Generated by Django 5.2.4 on 2025-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_result_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('link', models.URLField()),
                ('bg_color', models.CharField(default='primary', help_text='Bootstrap background color (e.g. danger, primary, success)', max_length=20)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
