# Generated by Django 5.2.4 on 2025-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_highlightpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
