# Generated by Django 5.2.4 on 2025-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admitcard_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightpost',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='highlightpost',
            name='link',
        ),
        migrations.RemoveField(
            model_name='highlightpost',
            name='post_count',
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='content',
            field=models.TextField(default='No content available'),
        ),
    ]
