# Generated by Django 5.2.4 on 2025-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_highlightpost_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightpost',
            name='content',
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='bg_color',
            field=models.CharField(default='primary', help_text='Bootstrap background color (e.g. danger, primary, success)', max_length=20),
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
