# Generated by Django 5.2.4 on 2025-07-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_highlightpost_content_highlightpost_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='age_limit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='how_to_apply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='important_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='important_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='total_posts',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
