# Generated by Django 5.2.4 on 2025-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jobpost_age_limit_jobpost_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='exam_fee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
