# Generated by Django 5.2.4 on 2025-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='total_posts',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
