# Generated by Django 5.2.4 on 2025-08-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jobpost_total_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='total_posts',
            field=models.TextField(blank=True),
        ),
    ]
