# Generated by Django 5.2.4 on 2025-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobpost_total_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='apply_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(),
        ),
    ]
