# Generated by Django 5.2.4 on 2025-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_jobpost_apply_link_alter_jobpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('answer_key_link', models.TextField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('notice_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='admitcard',
            name='category',
            field=models.CharField(default='Latest Admit Card', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admitcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='notification_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='notification_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='category',
            field=models.CharField(default='Latest Admit Card', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='notification_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='category',
            field=models.CharField(default='Latest Admit Card', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='notification_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='title',
            field=models.TextField(default='Latest Admit Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='highlightpost',
            name='bg_color',
            field=models.CharField(default='primary', help_text='Bootstrap color (e.g., primary, success, danger)', max_length=20),
        ),
        migrations.AlterField(
            model_name='highlightpost',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='total_posts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
