# Generated by Django 5.2.4 on 2025-08-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_admission_answerkey_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admitcard',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='full_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
